### PR TITLE
Support selection of Chrome DevTools protocol version (and fixes current version which is incomplete)

### PR DESCRIPTION
**Pull request by holsee**
* Adds support for selecting different versions of the Chrome DevTools protocol through environment variables, defaulting to version "1-3".
* Adds all protocols "1-2", "1-3" and "tot" to `./priv`.
* Fixes issue with `./priv/protocol.json` whereby it was missing many of the domains which are contained within "1-3".

### CODE REVIEW

**Comment by andrewvy** [comment]
I'm a bit iffy about introducing a `CRI_PROTOCOL_VERSION` environment variable for a compile-flag, can we use Mix config and read it at compile-time?

A quick fix, I should make a mix task to fetch these from https://github.com/ChromeDevTools/debugger-protocol-viewer/tree/master/_data as a quick standardization.

**Comment by holsee** [comment]
Regarding the refresh of the protocol files I would recommend that discussion be moved to another issue.

Regarding compile time configuration:
* using config.ex is seen as an anti-pattern in libraries (see elixir 1.9 where it won’t be generated by default anymore on mix new)
* app config is read and populated for access at runtime, and as such won’t be suitable for compile time access
* environment variables are commonly used for configuring this kind of thing and work well in many scenarios including creating docker images.

**Comment by andrewvy** [comment]
Hmm, I'm still iffy on the changes, it's odd to me since Logger configuration also provides compile-time flags to purge log levels from code.

If you insist, I merged it in, we can always change this in the future.

**Comment by holsee** [comment]
I agree we can look at this again.  Maybe my understanding is flawed, but app configuration is certainly a runtime thing, maybe it is accessible from elixir compiler which hydrates it 🤔, but in the meantime, the default behaviour remains unchanged and the option is there for those who wish to alter the protocol compile target.

Thanks!

**Comment by andrewvy** [comment]
Definitely! I think it's odd that application configuration is available at both compile-time + run-time, though I agree the primary usage is 99% runtime-based configuration. I've never had the chance to deal with compile-time flags in an Elixir lib before too. :smile: 

Thanks for the PR!

**Pull request merged**
